export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const INCREMENT_TYPE = 'INCREMENT_TYPE';
export const DECREMENT_TYPE = 'DECREMENT_TYPE';
export const UNDO_TYPE = 'UNDO_TYPE';
export const REDO_TYPE = 'REDO_TYPE';


export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const SELECT_REDDIT = 'SELECT_REDDIT';
export const INVALIDATE_REDDIT = 'INVALIDATE_REDDIT';

